services:
  kakarot-rpc:
    image: ghcr.io/kkrt-labs/kakarot-rpc/node:v0.7.0-alpha7
    pull_policy: always
    volumes:
      # Mount the indexer code
      - indexer_code_prod:/usr/src/indexer

  apibara-dna:
    image: quay.io/apibara/starknet:1.5.0
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - start
      - --rpc=https://juno-kakarot-sepolia.karnot.xyz
      - --wait-for-rpc
      - --data=/data
      - --head-refresh-interval-ms=1000
      - --dangerously-override-ingestion-start-block=219010
    ports:
      - 7171:7171
    volumes:
      - apibara_prod:/data
    networks:
      - internal_prod
    restart: on-failure

  ### MongoDB with Mongo Express
  mongo:
    image: mongo:6.0.8
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 27017:27017
    volumes:
      - mongo_data_prod:/data/db
    networks:
      - internal_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  indexer:
    image: quay.io/apibara/sink-mongo:0.7.1
    command:
      - run
      - /indexer/src/main.ts
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      # Whitelist environment variables
      - ALLOW_ENV_FROM_ENV=DEBUG,APIBARA_AUTH_TOKEN,STARTING_BLOCK,STREAM_URL,SINK_TYPE,MONGO_CONNECTION_STRING,MONGO_DATABASE_NAME,STARKNET_NETWORK,KAKAROT_ADDRESS,ALLOW_NET,MONGO_REPLACE_DATA_INSIDE_TRANSACTION,DEFAULT_BLOCK_GAS_LIMIT
      - DEBUG=""
      - APIBARA_AUTH_TOKEN=""
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
      - STARTING_BLOCK=219015
      - STREAM_URL=http://apibara-dna:7171
      - SINK_TYPE=mongo
      - STARKNET_NETWORK=https://juno-kakarot-sepolia.karnot.xyz
      - ALLOW_NET=
      - MONGO_REPLACE_DATA_INSIDE_TRANSACTION=false
      - KAKAROT_ADDRESS=0x78bd079b79aa45111313f200a22e5c52ff7526c746d73b65672cc28acbe2263
      - DEFAULT_BLOCK_GAS_LIMIT=7000000
    restart: on-failure
    volumes:
      - indexer_code_prod:/indexer
    networks:
      - internal_prod

networks:
  internal_prod:
    driver: bridge
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  apibara_prod:
  mongo_data_prod:
  indexer_code_prod:
  pgadmin_data_prod:
  juno_files_prod:
  postgres_data_prod:
  redis_data_prod:
