# trunk-ignore-all(yamllint/empty-values)
version: "3.2"

services:
  starknet:
    image: greged93/madara:v0.6.0
    ports:
      - 9615:9615
      - 9944:9944
      - 30333:30333
      - 5050:5050
    entrypoint: [/bin/bash, -c]
    command: >
      "/madara-bin setup --from-remote --chain=dev && /madara-bin --rpc-external --rpc-methods=unsafe --rpc-cors=all --rpc-port 5050 --chain=dev --base-path=/home/madara --alice --force-authoring"
    volumes:
      - madara:/home/madara
    networks:
      - internal
    restart: on-failure

  kakarot-deployer:
    extends:
      file: docker-compose.yaml
      service: kakarot-deployer
    environment:
      - ACCOUNT_ADDRESS=0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973
      - PRIVATE_KEY=0x1800000000300000180000000000030000000000003006001800006600
      - EVM_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

  deployments-parser:
    extends:
      file: docker-compose.yaml
      service: deployments-parser

  kakarot-rpc:
    extends:
      file: docker-compose.yaml
      service: kakarot-rpc

  apibara-dna:
    extends:
      file: docker-compose.yaml
      service: apibara-dna

  mongo:
    extends:
      file: docker-compose.yaml
      service: mongo

  clone-repo:
    extends:
      file: docker-compose.yaml
      service: clone-repo

  indexer:
    extends:
      file: docker-compose.yaml
      service: indexer

networks:
  internal:

volumes:
  deployments:
  apibara:
  mongo_data:
  indexer_code:
