name: Dump the Katana state into the .katana folder

on:
  workflow_call:

jobs:
  dump:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Load cached submodules
        id: cached-submodules
        uses: actions/cache@v3
        with:
          path: ./lib/
          key: ${{ runner.os }}-submodules
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      # Load lib submodules
      - name: Load submodules
        id: cached-submodules
        uses: actions/cache/restore@v3
        with:
          path: ./lib/
          key: ${{ runner.os }}-submodules
      - name: Generate the Katana dumped state
        run: ./scripts/make_with_env.sh dump-katana
      - name: Save dump as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dump-katana
          path: ./.katana/
