---
name: RPC

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    strategy:
      matrix:
        include:
          # - dockerfile: ./docker/rpc/Dockerfile
          #   image: ghcr.io/${{ github.repository }}/node
          - dockerfile: ./docker/hive/Dockerfile
            image: ghcr.io/${{ github.repository }}/node-hive
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ matrix.image }}:latest
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
