---
name: Workflow - Pull Request

on: [pull_request]

jobs:
  dump:
    name: Dump katana state
    uses: ./.github/workflows/dump.yml

  spell_check:
    name: Spell check
    uses: ./.github/workflows/spell_check.yml

  linters:
    name: Linters
    uses: ./.github/workflows/linters.yml

  tests:
    name: Rust tests
    uses: ./.github/workflows/test.yml
    needs: dump
