---
name: Workflow - Push

on:
  push:
    branches: [main]

jobs:
  dump:
    name: Dump katana state
    uses: ./.github/workflows/dump.yml

  spell_check:
    name: Spell check
    uses: ./.github/workflows/spell_check.yml

  benchmark:
    name: Erc20 benchmark
    uses: ./.github/workflows/benchmark.yml

  build:
    name: Build binaries
    uses: ./.github/workflows/kakarot_rpc.yml
